# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class SnpCrawlerItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass


class EnsembleVariationItem(scrapy.Item):
    _id = scrapy.Field()  # used for mongodb
    name = scrapy.Field()
    MAF = scrapy.Field()
    source = scrapy.Field()
    ancestral_allele = scrapy.Field()
    minor_allele = scrapy.Field()
    ambiguity = scrapy.Field()
    mappings = scrapy.Field()
    clinical_significance = scrapy.Field()
    var_class = scrapy.Field()
    synonyms = scrapy.Field()
    evidence = scrapy.Field()
    most_severe_consequence = scrapy.Field()
    phenotypes = scrapy.Field()
    genotypes = scrapy.Field()
    populations = scrapy.Field()
    population_genotypes = scrapy.Field()
    updated_at = scrapy.Field()


class DbSnpItem(scrapy.Item):
    _id = scrapy.Field()  # used for mongodb
    name = scrapy.Field()
    allele_origin = scrapy.Field()
    global_maf = scrapy.Field()
    clinical_significance = scrapy.Field()
    gene = scrapy.Field()
    acc = scrapy.Field()
    chr = scrapy.Field()
    validated = scrapy.Field()
    create_build_id = scrapy.Field()
    modified_build_id = scrapy.Field()
    snp_class = scrapy.Field()
    pos = scrapy.Field()
    contigpos = scrapy.Field()
    updated_at = scrapy.Field()


class DeafnessItem(scrapy.Item):
    _id = scrapy.Field()  # used for mongodb
    variation = scrapy.Field()
    gene = scrapy.Field()
    hgvs_protein_change = scrapy.Field()
    hgvs_nucleotide_change = scrapy.Field()
    variantlocale = scrapy.Field()
    pathogenicity = scrapy.Field()
    disease = scrapy.Field()
    pubmed_id = scrapy.Field()
    dbsnp = scrapy.Field()
    summary_insilico = scrapy.Field()
    summary_frequency = scrapy.Field()
    summary_published = scrapy.Field()
    comments = scrapy.Field()
    lrt_omega = scrapy.Field()
    phylop_score = scrapy.Field()
    phylop_pred = scrapy.Field()
    sift_score = scrapy.Field()
    sift_pred = scrapy.Field()
    polyphen2_score = scrapy.Field()
    polyphen2_pred = scrapy.Field()
    lrt_score = scrapy.Field()
    lrt_pred = scrapy.Field()
    mutationtaster_score = scrapy.Field()
    mutationtaster_pred = scrapy.Field()
    gerp_nr = scrapy.Field()
    gerp_rs = scrapy.Field()
    gerp_pred = scrapy.Field()
    evs_ea_ac = scrapy.Field()
    evs_ea_an = scrapy.Field()
    evs_ea_af = scrapy.Field()
    evs_aa_ac = scrapy.Field()
    evs_aa_an = scrapy.Field()
    evs_aa_af = scrapy.Field()
    evs_all_ac = scrapy.Field()
    evs_all_an = scrapy.Field()
    evs_all_af = scrapy.Field()
    otoscope_aj_ac = scrapy.Field()
    otoscope_aj_an = scrapy.Field()
    otoscope_aj_af = scrapy.Field()
    otoscope_co_ac = scrapy.Field()
    otoscope_co_an = scrapy.Field()
    otoscope_co_af = scrapy.Field()
    otoscope_us_ac = scrapy.Field()
    otoscope_us_an = scrapy.Field()
    otoscope_us_af = scrapy.Field()
    otoscope_jp_ac = scrapy.Field()
    otoscope_jp_an = scrapy.Field()
    otoscope_jp_af = scrapy.Field()
    otoscope_es_ac = scrapy.Field()
    otoscope_es_an = scrapy.Field()
    otoscope_es_af = scrapy.Field()
    otoscope_tr_ac = scrapy.Field()
    otoscope_tr_an = scrapy.Field()
    otoscope_tr_af = scrapy.Field()
    otoscope_all_ac = scrapy.Field()
    otoscope_all_an = scrapy.Field()
    otoscope_all_af = scrapy.Field()
    tg_afr_ac = scrapy.Field()
    tg_afr_an = scrapy.Field()
    tg_afr_af = scrapy.Field()
    tg_eur_ac = scrapy.Field()
    tg_eur_an = scrapy.Field()
    tg_eur_af = scrapy.Field()
    tg_amr_ac = scrapy.Field()
    tg_amr_an = scrapy.Field()
    tg_amr_af = scrapy.Field()
    tg_eas_ac = scrapy.Field()
    tg_eas_an = scrapy.Field()
    tg_eas_af = scrapy.Field()
    tg_sas_ac = scrapy.Field()
    tg_sas_an = scrapy.Field()
    tg_sas_af = scrapy.Field()
    tg_all_ac = scrapy.Field()
    tg_all_an = scrapy.Field()
    tg_all_af = scrapy.Field()
    exac_afr_ac = scrapy.Field()
    exac_afr_an = scrapy.Field()
    exac_afr_af = scrapy.Field()
    exac_amr_ac = scrapy.Field()
    exac_amr_an = scrapy.Field()
    exac_amr_af = scrapy.Field()
    exac_eas_ac = scrapy.Field()
    exac_eas_an = scrapy.Field()
    exac_eas_af = scrapy.Field()
    exac_fin_ac = scrapy.Field()
    exac_fin_an = scrapy.Field()
    exac_fin_af = scrapy.Field()
    exac_nfe_ac = scrapy.Field()
    exac_nfe_an = scrapy.Field()
    exac_nfe_af = scrapy.Field()
    exac_oth_ac = scrapy.Field()
    exac_oth_an = scrapy.Field()
    exac_oth_af = scrapy.Field()
    exac_sas_ac = scrapy.Field()
    exac_sas_an = scrapy.Field()
    exac_sas_af = scrapy.Field()
    exac_all_ac = scrapy.Field()
    exac_all_an = scrapy.Field()
    exac_all_af = scrapy.Field()
    updated_at = scrapy.Field()


class GwasAssociationItem(scrapy.Item):
    _id = scrapy.Field()
    added_date = scrapy.Field()
    pmid = scrapy.Field()
    first_author = scrapy.Field()
    pub_date = scrapy.Field()
    journal = scrapy.Field()
    link = scrapy.Field()
    study = scrapy.Field()
    trait = scrapy.Field()
    initial_sample = scrapy.Field()
    replica_sample = scrapy.Field()
    region = scrapy.Field()
    chr = scrapy.Field()
    pos = scrapy.Field()
    reported_gene = scrapy.Field()
    mapped_gene = scrapy.Field()
    upstream_gene = scrapy.Field()
    downstream_gene = scrapy.Field()
    gene_ids = scrapy.Field()
    upstream_gene_dis = scrapy.Field()
    downstream_gene_dis = scrapy.Field()
    snp_risk = scrapy.Field()
    snp = scrapy.Field()
    merged = scrapy.Field()
    snp_current = scrapy.Field()
    context = scrapy.Field()
    intergenic = scrapy.Field()
    risk_freq = scrapy.Field()
    pvalue = scrapy.Field()
    pvalue_mlog = scrapy.Field()
    pvalue_text = scrapy.Field()
    or_beta = scrapy.Field()
    ci95 = scrapy.Field()
    platform = scrapy.Field()
    cnv = scrapy.Field()
    mapped_trait = scrapy.Field()
    mapped_trait_uri = scrapy.Field()
    study_accession = scrapy.Field()
